export const ProjectConstants = [
  {
    imgPath: require("../../Assets/Projects/LawgicBot.png"),
    title: "LawgicBot",
    desc: "Full-stack legal education platform featuring AI agent workflows, RAG-powered FastAPI backend, Nextjs frontend, and automated PDF generation - with conversational AI, real-time document creation, and deployed on Google Cloud with zero data retention architecture.",
    demoLink: "https://dallas-ai-psi.vercel.app",
  },
  {
    imgPath: require("../../Assets/Projects/BasketballAnalytics.png"),
    title: "Basketball Analytics",
    desc: "Built a comprehensive prediction system using 7 years of college basketball data (2,136+ team records) from BartTorvik.com. Developed three ML models achieving 95.2% AUC for tournament qualification, 90.4% for upset detection, and 89.7% for deep-run predictions.",
    demoLink: "https://basketball-analytical-tool.vercel.app",
  },
  {
    imgPath: require("../../Assets/Projects/BigDataProject.jpg"),
    title: "Big Data Project",
    desc: "Build this project utilizing machine learning models (like Random Forest, Logistic Regression and Support Vector Machine), Fast API, Nextjs and Vercel to predict the risk of heart attack based on user-provided health metrics such as age, cholesterol level, exercise habits, stress level, and BMI.",
    demoLink: "https://big-data-project.vercel.app",
  },
  {
    imgPath: require("../../Assets/Projects/20Vision.png"),
    title: "20Vision",
    desc: "20Vision is a social network designed to improve humanity's understanding and collaboration.It is a knowledge-sharing platform along with innovative projects.",
    demoLink: "https://www.20.vision/discover",
  },
  {
    imgPath: require("../../Assets/Projects/eudaimoniaWiki.png"),
    title: "Eudaimonia Wiki",
    desc: "The eudaimonia project's goal is to crowd-curate a continuously self-updating, ranked collection of humanity's most useful wisdom. It was created using Nextjs, Firestore, Nestjs along with Google Cloud Platform.",
    demoLink: "https://www.eudaimonia.wiki/",
  },
  {
    imgPath: require("../../Assets/Projects/EatPreparie.png"),
    title: "Eat Preparie",
    desc: "Preparie is a food system built from scratch using Next.js and Ant Design along with AWS Lambda and serverless to connect local, food safety-certified cooks with an online marketplace to connect with customers in their community and sell homemade dishes.",
    demoLink: "https://www.eatpreparie.com",
  },
  {
    imgPath: require("../../Assets/Projects/LessonPlan.png"),
    title: "DSS Lesson Plan",
    desc: "A web application in which students can examine their weekly schedules for school, and teachers are responsible for inputting details regarding classwork and assignments. React.js and React Bootstrap, along with a REST API using Laravel and MongoDB, were used in its development.",
    demoLink: "https://lessonplansifal.dwit.edu.np",
    vercelLink: "https://lesson-plan-react-deploy.vercel.app/",
  },
  {
    imgPath: require("../../Assets/Projects/SifalSchool.png"),
    title: "Sifal School",
    desc: "It is an online portal that was created using Laravel and inertia.js to provide parents, students, teachers, and the community with timely, interesting, and current information regarding the school and its activities.",
    demoLink: "https://deerwalk.edu.np/sifalschool/",
  },
  {
    imgPath: require("../../Assets/Projects/DWITNews.png"),
    title: "DWIT News",
    desc: "DWIT News is the first and only online newspaper in Nepal that is entirely managed and run by college students and built using Laravel.",
    demoLink: "https://dwitnews.com/",
  },
  {
    imgPath: require("../../Assets/Projects/InternManager.png"),
    title: "Intern Manager",
    desc: "The Intern Manager is a web-based platform that simplifies program management for interns with the goal of facilitating continuous communication between them and their manager to ease their day-to-day activities.",
    demoLink: "https://internmanager.deerwalk.edu.np",
  },
  {
    imgPath: require("../../Assets/Projects/FYPWebApp.png"),
    title: "Offline Answer Sheet Submission Web Portal",
    desc: "A web application that allows teachers and administrators to upload question papers, which are then encrypted using AES and stored in IPFS to verify the authenticity and hash key of the files sent by students. It was built using React and Web3j, as well as Blockchain technologies such as Solidity, Metamask, and Ethereum.",
    gitHubLink: "https://github.com/tayouthae/FinalYearProject",
  },
  {
    imgPath: require("../../Assets/Projects/MicroProject.png"),
    title: "Notify Deerwalker",
    desc: "Notify Deerwalker is a mobile application built using web scraping technology (Beautiful Soup) and the Flutter library to display and notify students about the assignments or notices uploaded by their respective teachers or professors with the help of the Firebase Database.",
    gitHubLink: "https://github.com/tayouthae/MicroProject",
  },
  {
    imgPath: require("../../Assets/Projects/MiniProject.png"),
    title: "Fitness App",
    desc: "A system that uses technology and sports science to assist users in maintaining a healthy lifestyle by measuring steps, food intake, calories, and mental wellness using Flutter and Firebase.",
    gitHubLink: "https://github.com/tayouthae/Fitness-App-Mini-Project",
  },
  {
    imgPath: require("../../Assets/Projects/FYPMobileApp.png"),
    title: "Offline Answer Sheet Submission Mobile App",
    desc: "Mobile application for students to perform basic CRUD operations on question papers as well as answer sheets without the need for a valid internet connection, which was using Flutter and Firebase, communicating with the RESTful API built using Spring Boot (Java) and Twilio SMS as PaaS.",
    gitHubLink: "https://github.com/tayouthae/FinalYearProject",
  },
];
